language: java
jdk: oraclejdk8
before_cache:
  - rm -f  $HOME/.gradle/caches/modules-2/modules-2.lock
  - rm -fr $HOME/.gradle/caches/*/plugin-resolution/
cache:
  directories:
    - $HOME/.gradle/caches/
    - $HOME/.gradle/wrapper/
before_install:
  - curl -sSLO https://github.com/shyiko/ktlint/releases/download/0.8.3/ktlint
  - chmod +x ktlint
  - chmod +x gradlew
script:
  - ./gradlew build
  - ./ktlint
after_success: ./gradlew cobertura coveralls
